### ISSUE TITLE
is this crawler working ?

### ISSUE THREAD

**Issue by shahreahang** [huaying/instagram-crawler#104]
Hello,

I tested this crawler in both windows and linux without any success.
Here is what error I receive :

```
C:\inscrawler>python crawler.py hashtag -t taiwan -o ./output

DevTools listening on ws://127.0.0.1:3035/devtools/browser/a2ff5c1b-b79b-47e7-99ef-db15bbcc97b3
Traceback (most recent call last):
  File "C:\inscrawler\crawler.py", line 96, in <module>
    get_posts_by_hashtag(args.tag, args.number or 100, args.debug), args.output
  File "C:\inscrawler\crawler.py", line 42, in get_posts_by_hashtag
    ins_crawler = InsCrawler(has_screen=debug)
  File "C:\inscrawler\inscrawler\crawler.py", line 70, in __init__
    self.login()
  File "C:\inscrawler\inscrawler\crawler.py", line 87, in login
    login_btn.click()
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP  L3NKy   y3zKF     " disabled="" type="submit">...</button> is not clickable at point (400, 243). Other element would receive the click: <div class="_7UhW9   xLCgt      MMzan   _0PwGv         uL8Hv         ">...</div>
  (Session info: headless chrome=86.0.4240.111)


C:\inscrawler>
```

Is it just me ? or its not working anymore ??

**Comment by ZIMMERMANN-Nicolas** [comment]
Same for me on windows

**Comment by proseuche** [comment]
I just solve this problem by removing lines in `secret.py` and write like

```
username = 'your_id'
password = 'your_password'
```

I think it's because it tries to login with your Windows user name.

**Comment by paperplan3** [comment]
same problem, i did also change to username = 'your_id' but problem still continues
