### ISSUE TITLE
I have disapointed :(  it is not working

### ISSUE THREAD

**Issue by rsa408** [huaying/instagram-crawler#107]
I installed requirements and changed the User and Password.

```
λ python crawler.py hashtag -t Life -o ./output --fetch_details

DevTools listening on ws://127.0.0.1:7031/devtools/browser/c98d49da-9034-4d32-8591-32b5eff7b051
[1207/224709.954:ERROR:command_buffer_proxy_impl.cc(122)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[1207/224713.804:INFO:CONSOLE(401)] "Uncaught (in promise) undefined", source: https://www.instagram.com/static/bundles/metro/ConsumerLibCommons.js/ebead6081010.js (401)
Traceback (most recent call last):
  File "crawler.py", line 96, in <module>
    get_posts_by_hashtag(args.tag, args.number or 100, args.debug), args.output
  File "crawler.py", line 42, in get_posts_by_hashtag
    ins_crawler = InsCrawler(has_screen=debug)
  File "D:\instagram-crawler-master\inscrawler\crawler.py", line 70, in __init__
    self.login()
  File "D:\instagram-crawler-master\inscrawler\crawler.py", line 87, in login
    login_btn.click()
AttributeError: 'NoneType' object has no attribute 'click'
```

**Comment by hamitaksln** [comment]
You can use this for now. I've requested for pulling.
https://github.com/hamitaksln/instagram-crawler

**Comment by konka95git** [comment]
> You can use this for now. It works. I've requested for pulling.
> https://github.com/hamitaksln/instagram-crawler

Hi there, thanks so much for your help. It works somehow but the results still cannot write to the output folder:
I got the following error:

```
Exception ignored in: <function Popen.__del__ at 0x00000266D0695040>
Traceback (most recent call last):
  File "D:\Python\lib\subprocess.py", line 945, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "D:\Python\lib\subprocess.py", line 1344, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
```

Thanks in advance for your reply :) Really appreciate it!
KL

**Comment by konka95git** [comment]
> I installed requirements and changed the User and Password.
> 
> ```
> λ python crawler.py hashtag -t Life -o ./output --fetch_details
> 
> DevTools listening on ws://127.0.0.1:7031/devtools/browser/c98d49da-9034-4d32-8591-32b5eff7b051
> [1207/224709.954:ERROR:command_buffer_proxy_impl.cc(122)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
> [1207/224713.804:INFO:CONSOLE(401)] "Uncaught (in promise) undefined", source: https://www.instagram.com/static/bundles/metro/ConsumerLibCommons.js/ebead6081010.js (401)
> Traceback (most recent call last):
>   File "crawler.py", line 96, in <module>
>     get_posts_by_hashtag(args.tag, args.number or 100, args.debug), args.output
>   File "crawler.py", line 42, in get_posts_by_hashtag
>     ins_crawler = InsCrawler(has_screen=debug)
>   File "D:\instagram-crawler-master\inscrawler\crawler.py", line 70, in __init__
>     self.login()
>   File "D:\instagram-crawler-master\inscrawler\crawler.py", line 87, in login
>     login_btn.click()
> AttributeError: 'NoneType' object has no attribute 'click'
> ```

I think you may want to get the content from private ins account which can not be done. So you got this error.
