### ISSUE TITLE
selenium.common.exceptions.ElementClickInterceptedException

### ISSUE THREAD

**Issue by imnimesh** [huaying/instagram-crawler#115]
Traceback (most recent call last):
  File "crawler.py", line 83, in <module>
    args.username, args.number, args.mode == "posts_full", args.debug
  File "crawler.py", line 27, in get_posts_by_user
    ins_crawler = InsCrawler(has_screen=debug)
  File "/Users/nimesh/.Trash/instagram-crawler-master/inscrawler/crawler.py", line 70, in __init__
    self.login()
  File "/Users/nimesh/.Trash/instagram-crawler-master/inscrawler/crawler.py", line 87, in login
    login_btn.click()
  File "/Users/nimesh/anaconda3/envs/untitled/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/nimesh/anaconda3/envs/untitled/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Users/nimesh/anaconda3/envs/untitled/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/nimesh/anaconda3/envs/untitled/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP  L3NKy   y3zKF     " disabled="" type="submit">...</button> is not clickable at point (400, 265). Other element would receive the click: <div class="                     Igw0E     IwRSH      eGOV_         _4EzTm    bkEs3                          CovQj                  jKUp7          DhRcB                                                    ">...</div>
  (Session info: headless chrome=89.0.4389.114)

**Comment by qlofly** [comment]
Based on the error, you are trying to click on an element that does not support click on it. 
You need to select a different item to click

**Comment by blubdiblah** [comment]
There may be an "Accept Cookies" modal covering the login button.
As quick fix I just added following after `browser.get(url)` in the login() function:

`accept_cookies = browser.find_one(".bIiDR")`
        `if accept_cookies is not None:`
            `accept_cookies.click()`
            `time.sleep(5)`
