### ISSUE TITLE
login doesn't work

### ISSUE THREAD

**Issue by mimixtvxq** [huaying/instagram-crawler#13]
Hi Huaying, thanks for your crawler! 

I am trying to use liker.py and the code seems to work (briefly) but it diverts back to the login page since it isn't logged in to the user and then app crashes. I have already set my own password and username in the secret file but it still won't log in. 

Thank you! 

Here is the log file:

`Traceback (most recent call last):
  File "liker.py", line 22, in <module>
    ins_crawler.auto_like(tag=args.hashtag, maximum=args.number)
  File "/Users/mimichindasook/Downloads/instagram-crawler-master/inscrawler/crawler.py", line 112, in auto_like
    ele_post.click()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a href="/p/BoXEX4hhapD/?tagged=surf">...</a> is not clickable at point (132, 473). Other element would receive the click: <div class="pHxcJ">...</div>
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.11.6 x86_64)
`

**Comment by huaying** [comment]
It seems that you didn't log in to Instagram successfully. 
Make sure you already set the account and password in `secret.py`(not `secret.py.dist`).
```
username = os.environ.get('USERNAME', 'your account')
password = os.environ.get('PASSWORD', 'your password')
```

Good luck :)

**Comment by mimixtvxq** [comment]
Ah got it! Thank you so much!
