### ISSUE TITLE
Small? Error in post_full

### ISSUE THREAD

**Issue by philipperemy** [huaying/instagram-crawler#23]
Trying to scrape: https://www.instagram.com/explore/tags/satoyamaexperience/

```
python crawler.py posts_full -t satoyamaexperience -n 1000 -o ./output
```

Error
```
Traceback (most recent call last):
  File "crawler.py", line 77, in <module>
    args.debug
  File "crawler.py", line 25, in get_posts_by_user
    return ins_crawler.get_user_posts(username, number, detail)
  File "/Users/philipperemy/PycharmProjects/instagram-crawler/inscrawler/crawler.py", line 100, in get_user_posts
    user_profile = self.get_user_profile(username)
  File "/Users/philipperemy/PycharmProjects/instagram-crawler/inscrawler/crawler.py", line 89, in get_user_profile
    post_num, follower_num, following_num = statistics
ValueError: not enough values to unpack (expected 3, got 0)
```

Thanks a million in advance :)

**Comment by philipperemy** [comment]
@huaying Let me know if you need more info! Btw this repo looks pretty solid!

**Comment by philipperemy** [comment]
Actually running this works:

```
python crawler.py hashtag -t satoyamaexperience -n 1000 -o ./output
```

**Comment by huaying** [comment]
Yes, `-t` only works in `hashtag` mode  :)
