### ISSUE TITLE
add elment date time

### ISSUE THREAD

**Issue by azmi155** [huaying/instagram-crawler#35]
we need date time to analys

**Comment by huaying** [comment]
You can use the mode `posts_full` to get the datetime

**Comment by azmi155** [comment]
how i get date time but i want crawl by hastag

**Comment by azmi155** [comment]
python crawler.py posts_full -t pashmina -n 100 -o ./full.json
Traceback (most recent call last):
  File "crawler.py", line 77, in <module>
    args.debug
  File "crawler.py", line 25, in get_posts_by_user
    return ins_crawler.get_user_posts(username, number, detail)
  File "/home/newbie/instagram-crawler/inscrawler/crawler.py", line 105, in get_user_posts
    user_profile = self.get_user_profile(username)
  File "/home/newbie/instagram-crawler/inscrawler/crawler.py", line 94, in get_user_profile
    post_num, follower_num, following_num = statistics
ValueError: need more than 0 values to unpack
