### ISSUE TITLE
Failed to fetch the post

### ISSUE THREAD

**Issue by LeeHanYeong** [huaying/instagram-crawler#38]
An error occurs when crawling user dain __. 070528

The traceback is shown below
```
fetching:  29%|█████████████████████████████████████████████▋                                                                                                              | 12/41 [01:01<02:23,  4.94s/it]Failed to fetch the post: https://www.instagram.com/p/BuEe8f_DeA5/

Traceback (most recent call last):
  File "/Users/lhy/projects/10wonders/app/inscrawler/crawler.py", line 286, in _get_posts_full
    self._fetch_post_with_key(cur_key, dict_post)
  File "/Users/lhy/projects/10wonders/app/inscrawler/crawler.py", line 183, in _fetch_post_with_key
    img_urls.add(ele_img.get_attribute('src'))
  File "/usr/local/var/pyenv/versions/3.7.2/envs/10wonders/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 143, in get_attribute
    resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
  File "/usr/local/var/pyenv/versions/3.7.2/envs/10wonders/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/var/pyenv/versions/3.7.2/envs/10wonders/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/var/pyenv/versions/3.7.2/envs/10wonders/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.6 x86_64)
```

**Comment by huaying** [comment]
Yeah it's flaky. I need to do more research.
