### ISSUE TITLE
Instagram Like featching problem

### ISSUE THREAD

**Issue by andp97** [huaying/instagram-crawler#58]
`
Failed to fetch the post: https://www.instagram.com/p/B1zBXiygROa/Traceback (most recent call last):
  File "instagram-crawler/inscrawler/crawler.py", line 213, in _get_posts_full
    fetch_likers(browser, dict_post)
  File "instagram-crawler/inscrawler/fetch.py", line 93, in fetch_likers
    like_info_btn.click()
AttributeError: 'NoneType' object has no attribute 'click'
fetching: 100%|
[{"key": "https://www.instagram.com/p/B1zBXiygROa/", "datetime": "2019-08-30T17:54:17.000Z", "img_urls": ["https://scontent-mxp1-1.cdninstagram.com/vp/b4825b2b1f9fcadd1df00ef2629f22e0/5D6C7096/t51.2885-15/e35/69663551_128155128469835_2515122558944658279_n.jpg?_nc_ht=scontent-mxp1-1.cdninstagram.com"]}]
`

https://mixmag.net/read/instagram-remove-likes-trial-news

**Comment by rpryzant** [comment]
+1!
