### ISSUE TITLE
Getting Issue when trying to run example

### ISSUE THREAD

**Issue by Fritz609** [huaying/instagram-crawler#87]
I installed the pre-reqs and am running Anaconda python 3 . Command and error below

(base) PS C:\Users\fritz\git_projects\instagram-crawler> python crawler.py posts_full -u cal_foodie -n 100 -o ./output

DevTools listening on ws://127.0.0.1:56881/devtools/browser/c86d0392-0cec-44b7-85a4-853324b27bab
[0430/011623.931:INFO:CONSOLE(0)] "The resource https://www.instagram.com/static/bundles/metro/FBSignupPage.css/771caa625ac6.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
Traceback (most recent call last):
  File "crawler.py", line 83, in <module>
    args.username, args.number, args.mode == "posts_full", args.debug
  File "crawler.py", line 27, in get_posts_by_user
    ins_crawler = InsCrawler(has_screen=debug)
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\crawler.py", line 70, in __init__
    self.login()
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\crawler.py", line 94, in login
    check_login()
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\utils.py", line 21, in wrapped_f
    return retry(attempt - 1, wait)(func)(*args, **kwargs)
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\utils.py", line 21, in wrapped_f
    return retry(attempt - 1, wait)(func)(*args, **kwargs)
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\utils.py", line 21, in wrapped_f
    return retry(attempt - 1, wait)(func)(*args, **kwargs)
  [Previous line repeated 6 more times]
  File "C:\Users\fritz\git_projects\instagram-crawler\inscrawler\utils.py", line 25, in wrapped_f
    raise exc
inscrawler.exceptions.RetryException
(base) PS C:\Users\fritz\git_projects\instagram-crawler>

**Comment by kswgit** [comment]
Thank you for reporting but could you please check your username and password and those are correct?

**Comment by soeonkim** [comment]
if you use phone numeber for login, try to other info
ex) email, username

**Comment by Fritz609** [comment]
I got it to work. Thought I responded that I did in the GitHub comments but
maybe it didn't go through

**Comment by Shavindra** [comment]
@Fritz609  how did you get it to work?
