### ISSUE TITLE
Even basic commands don't work

### ISSUE THREAD

**Issue by tothlac** [huaying/instagram-crawler#93]
I'm constantly getting this error:

```python crawler.py posts_full -u barackobama  -n 100 -o ./output
Traceback (most recent call last):
  File "crawler.py", line 83, in <module>
    args.username, args.number, args.mode == "posts_full", args.debug
  File "crawler.py", line 27, in get_posts_by_user
    ins_crawler = InsCrawler(has_screen=debug)
  File "/Users/tothlac/otp/instagram-crawler/inscrawler/crawler.py", line 70, in __init__
    self.login()
  File "/Users/tothlac/otp/instagram-crawler/inscrawler/crawler.py", line 87, in login
    login_btn.click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP  L3NKy   y3zKF     " disabled="" type="submit">...</button> is not clickable at point (400, 320). Other element would receive the click: <div class="                    Igw0E     IwRSH      eGOV_         _4EzTm    bkEs3                          CovQj                  jKUp7          DhRcB                                                    ">...</div>
  (Session info: headless chrome=83.0.4103.116)```


Looks like even the basic functionality does not work. Please fix, or if it is not doable delete the useless repository.
Thanks.

**Comment by soeonkim** [comment]
Did you set the environment properly?
I tried it yesterday and it works except for some functions

**Comment by cmannerstrale** [comment]
I am getting the same error... Anyone know how to fix?
