### ISSUE TITLE
Error with posts_full

### ISSUE THREAD

**Issue by cmannerstrale** [huaying/instagram-crawler#94]
copying the first example call from readme and getting error message below: 
Any idea how to solve?

## Bug/Feature/Support
Traceback (most recent call last):
  File "crawler.py", line 83, in <module>
    args.username, args.number, args.mode == "posts_full", args.debug
  File "crawler.py", line 27, in get_posts_by_user
    ins_crawler = InsCrawler(has_screen=debug)
  File "/instagram-crawler-master/inscrawler/crawler.py", line 70, in __init__
    self.login()
  File "/instagram-crawler-master/inscrawler/crawler.py", line 87, in login
    login_btn.click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP  L3NKy   y3zKF     " disabled="" type="submit">...</button> is not clickable at point (400, 320). Other element would receive the click: <div class="                    Igw0E     IwRSH      eGOV_         _4EzTm    bkEs3                          CovQj                  jKUp7          DhRcB                                                    ">...</div>
  (Session info: headless chrome=84.0.4147.89)

**Comment by shahreahang** [comment]
did you solve this ??
